# Generated by Django 4.2.15 on 2024-09-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_modifed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='modifed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
