# Generated by Django 5.1.1 on 2024-10-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
